### ISSUE TITLE
prisma2 migration failed-mysql

### ISSUE THREAD

**Issue by rakeshrana15** [prisma/prisma-examples#1205] opened 2019-12-21 08:09 UTC
Migration failed  after running prisma2 dev command.

************************************************************
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:189:13)
    at C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:148922:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:148921:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\build\index.js:148907:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: kill ESRCH

***************************************************************************************************

Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 4466,
    "message": "The migration engine panicked while handling the request. Check the data field for details.",
    "data": {
      "message": "Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR 42S02 (1146): Table 'testdb._migration' doesn't exist')",
      "backtrace": null
    }
  },
  "id": 3
}
The migration engine panicked while handling the request. Check the data field for details.

Wrote failed-applyMigration-20191221130710.md with debugging information.
Please put that file into a gist and post it in Slack.
![prisma2 failed migration](https://user-images.githubusercontent.com/20044916/71305272-39b0be00-23f7-11ea-94df-ef99fe224bbc.png)
![prisma2 migration error](https://user-images.githubusercontent.com/20044916/71305275-41706280-23f7-11ea-8c1a-5d5458ffdffe.png)

**Comment by janpio** [comment] 2019-12-21 18:12
Duplicate of https://github.com/prisma/prisma2/issues/1202

**Closed by janpio** 2019-12-21 18:12 UTC
