### ISSUE TITLE
Epic: Deployment examples

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma-examples#4792] opened 2023-06-06 16:57 UTC
- [ ] Create or update the deployment starter examples
	- [ ] Azure Functions
	- [x] prisma/docs#5087
	- [x] prisma/docs#5291
	- [x] prisma/docs#5109
	- [x] prisma/prisma-examples#4799
	- [x] prisma/docs#5088
	- [ ] Cloudflare Workers
	- [ ] Deno Deploy
	- [ ] Google Cloud functions
- [ ] Remove Heroku example guides (dependent on https://github.com/prisma/docs/issues/4843)

**Comment by jharrell** [comment] 2023-07-18 16:56
Closing this as duplicate of prisma/prisma-examples#4721 

Moved all info over there.

**Closed as not planned by jharrell** 2023-07-18 16:56 UTC
