### ISSUE TITLE
The graphql examples are tooo repetitive

### ISSUE THREAD

**Issue by emahuni** [prisma/prisma-examples#898] opened 2019-10-25 07:15 UTC
I am not sure if there is something I am missing, but I think there is just too much repetition with this code.

```js
const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      pagination: false,
    })
  },
})
``` 

where as the same is defined elsewhere (which I actually prefer) in the `schema.prisma` file:

```graphql
model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}
```

Can't this example or the framework generate this Nexus code itself and provide a way to give it resolvers instead of repeating things like this. I can imagine when a change is done in the schema.prisma file and the followups that need to be done in a large application. I'd prefer it using the schema file as the source of truth, or at least give us a way to retrieve the definitions as regular graphql definitions that can be used with other Graphql libs including Nexus without repeating things like that.

**Comment by matthewmueller** [comment] 2019-10-28 17:24
@jasonkuhrt do you mind replying? :-)

**Comment by jasonkuhrt** [comment] 2019-10-28 20:55
Hey @emahuni I think this is a dupe of https://github.com/prisma-labs/nexus-prisma/issues/299. Your input over there is more than welcome 👍

**Closed by jasonkuhrt** 2019-10-28 20:55 UTC
Labels: process/candidate

**Comment by emahuni** [comment] 2019-10-29 06:00
ok sure thanks
