### ISSUE TITLE
Add Examples of using indexes add through `extendedIndexes` feature

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma-examples#3867] opened 2022-06-22 12:01 UTC
Examples on how to use indexes should be helpful: https://www.prisma.io/docs/concepts/components/prisma-schema/indexes

**Comment by janpio** [comment] 2022-06-22 14:22
The examples here are usually to show different frameworks and applications, not different parts of the schema. That is usually just documented in the docs. 

The problem is the complexity of the possibilities (all the relations, all the types, all the combinations...) which would make it either hard to a) put it all in one project or b) create different proejcts for each of those cases without ending up with dozens or hundreds of them.

Is there something concrete about the extended indexes that is unclear?

**Comment by nurul3101** [comment] 2022-06-23 16:38
Yes, it makes sense 👍 
Some users were asking for official GitHub repositories which would demonstrate using Gist, Gin, SpGist and BRIN types of indexes.

**Comment by ruheni** [comment] 2022-12-20 13:35
Closing this issue since we don't intend to add this to the examples.

**Closed as completed by ruheni** 2022-12-20 13:35 UTC
