### ISSUE TITLE
Typescript errors in fresh graphql-auth example

### ISSUE THREAD

**Issue by darknoon** [prisma/prisma-examples#968] opened 2019-11-12 20:26 UTC
I am trying to evaluate prisma2 for a data model and having trouble getting started. The example project has a typescript error. Deleting those lines broke the app.

I created the example with npx, you can check the logs below:

<details>
<summary>console log</summary>

```
$ npx prisma2 init hello-prisma

 SUCCESS  The hello-prisma directory was created!
 SUCCESS  Prisma is connected to your database at file:dev.db

┌─ Next steps ─────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                  │
│   Navigate into the project directory:                                                                           │
│   $ cd hello-prisma                                                                                              │
│                                                                                                                  │
│   Start Prisma's development mode to enable access to                                                            │
│   Prisma Studio and watch schema.prisma for changes:                                                             │
│   $ prisma2 dev                                                                                                  │
│                                                                                                                  │
│   Start the GraphQL server (in a new terminal window/tab):                                                       │
│   $ npm run dev                                                                                                  │
│                                                                                                                  │
│   Learn more about Prisma 2:                                                                                     │
│   https://github.com/prisma/prisma2/                                                                             │
│                                                                                                                  │
│   If you encounter any issues, please report them here:                                                          │
│   https://github.com/prisma/prisma-examples/issues/new                                                           │
│                                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


$ npx prisma2 dev

   Watching for changes in prisma/schema.prisma

   Watching for changes in prisma/schema.prisma

   Watching for changes in prisma/schema.prisma

   Watching for changes in prisma/schema.prisma
   Last changed at 2:47:50 PM


   Migrations
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save


   Generators
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Photon.js    Generated in 13.79s




```

</details>
<img width="483" alt="Screen Shot 2019-11-12 at 15 21 43" src="https://user-images.githubusercontent.com/355540/68707652-22f98a80-0560-11ea-9476-5e4463aff8a6.png">
<img width="768" alt="Screen Shot 2019-11-12 at 15 21 49" src="https://user-images.githubusercontent.com/355540/68707658-2725a800-0560-11ea-8aca-e533b46c60f2.png">

**Comment by AlexandruSerban142** [comment] 2019-11-13 16:13
I can confirm this issue, a solution would be very nice.

**Comment by izio38** [comment] 2019-11-15 18:15
Exacly same error here. Any workaround on this?

Prisma2 version: `prisma2@2.0.0-preview016.2`

**Comment by guog** [comment] 2019-11-18 03:42
I have a similar issue.

**Comment by darknoon** [comment] 2019-11-26 15:57
Just saw this thread on the slack, going to see if it fixes it
https://prisma.slack.com/archives/CKQTGR6T0/p1574760612437600?thread_ts=1574719609.430200&cid=CKQTGR6T0

**Comment by darknoon** [comment] 2019-11-26 16:00
Yes! That works for me, just add this block to your `schema.ts`: 

```ts
…
  outputs: {
    typegen: __dirname + '/generated/nexus.ts',
    schema: __dirname + '/generated/schema.graphql',
  },
…
```

**Comment by darrylyoung** [comment] 2019-11-27 08:37
Thanks, @darknoon. That works for me, too. 👍

**Comment by nikolasburk** [comment] 2019-11-27 08:38
Thanks for sharing the solution @darknoon 🙌 I'll close this issue and we'll update the examples today!

**Closed by nikolasburk** 2019-11-27 08:38 UTC
