### ISSUE TITLE
node folder not existed when cloning "git@github.com:prisma/prisma-examples.git"

### ISSUE THREAD

**Issue by Rezaavoor** [prisma/prisma-examples#1640] opened 2020-03-26 18:52 UTC
the cloned directory is different than what it should be

**Comment by nikolasburk** [comment] 2020-07-24 07:52
Hey @Rezaavoor, I'm closing this issue since there hasn't been any activity. Were you able to resolve this eventually? Please feel free to reopen the issue with a more precise description of the error so that we can reproduce and fix it 🙂

**Closed by nikolasburk** 2020-07-24 07:52 UTC
