### ISSUE TITLE
[javascript/graphql-apollo-server]: Unable to start example

### ISSUE THREAD

**Issue by brianbancroft** [prisma/prisma-examples#1734] opened 2020-04-18 03:20 UTC
Hi there, 

When I attempt to run this pared example [as per this set of directions](https://github.com/prisma/prisma-examples/blob/master/javascript/graphql-apollo-server/README.md), I run into the following error in the command line:
```
  Missing required typegen import: Context
```

This also manifests in the GraphQL Playground when I attempt to run _any_ query through the following:

<details><summary>Expand me for graphql response</summary>
<p>

```json
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"users\" on type \"Query\".",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"users\" on type \"Query\".",
              "    at Object.Field (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:213:34)",
              "    at Object.<anonymous> (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      },
      {
        "message": "Cannot query field \"user\" on type \"Query\".",
        "locations": [
          {
            "line": 9,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"user\" on type \"Query\".",
              "    at Object.Field (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:213:34)",
              "    at Object.<anonymous> (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      },
      {
        "message": "Cannot query field \"createUser\" on type \"Mutation\". Did you mean \"createDraft\"?",
        "locations": [
          {
            "line": 17,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"createUser\" on type \"Mutation\". Did you mean \"createDraft\"?",
              "    at Object.Field (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:213:34)",
              "    at Object.<anonymous> (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      },
      {
        "message": "Cannot query field \"updateUser\" on type \"Mutation\".",
        "locations": [
          {
            "line": 25,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"updateUser\" on type \"Mutation\".",
              "    at Object.Field (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:213:34)",
              "    at Object.<anonymous> (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      },
      {
        "message": "Cannot query field \"deleteUser\" on type \"Mutation\". Did you mean \"deleteOnePost\"?",
        "locations": [
          {
            "line": 33,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"deleteUser\" on type \"Mutation\". Did you mean \"deleteOnePost\"?",
              "    at Object.Field (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:213:34)",
              "    at Object.<anonymous> (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/Users/brianbancroft/programming/side-hustle/impressipies/graphql-apollo-server-api/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      }
    ]
  }
}
```

</p>
</details>

## Other pertinent details:

This was attempted with the latest LTS versions of Node, 12.16.2 and 10.20.0

**Comment by HendrikJan** [comment] 2020-04-24 10:29
I run into the same error (```Missing required typegen import: Context```) on Node 14.0.0  
The error message is preceded by another that might contain useful information:

    > node dist/server
    
    GraphQL Nexus Typegen: Expected module /data/dist/context.js to be an absolute path to a TypeScript module, skipping.
    
          🚀 Server ready at: http://localhost:3001
          ⭐️ See sample queries: http://pris.ly/e/ts/graphql-apollo-server#using-the-graphql-api
          
    Missing required typegen import: Context

**Comment by Benjaminryejones** [comment] 2020-05-13 08:48
In case you all haven't already fixed this, you can resolve the issue by renaming context.js to context.ts (you may need to support typescript imports in your main app)

**Comment by HendrikJan** [comment] 2020-05-14 19:17
@Benjaminryejones 
Thank you for the reply.

When I run `npm run build` the code runs without an error.  
This is in line with your comment, because there is a file named "context.ts" in the /src folder.  
This then generates a "context.js" file in the /dist folder.

When I then fun `npm run start` (which runs `node dist/server`), that is when the error appears.  
It does not feel right to rename this file to "context.ts" at this point.

I guess the problem is in the schema.ts file at this piece of code: 

```typescript
typegenAutoConfig: {
    contextType: 'Context.Context',
    sources: [
      {
        source: '@prisma/client',
        alias: 'prisma',
      },
      {
        source: require.resolve('./context'), // <-- problem here, I guess
        alias: 'Context',
      },
    ],
  },
```

Is there a way to make `npm run start` (`node dist/server`) to run without the error?

**Comment by imran-ib** [comment] 2020-07-31 06:56
Facing the Same Problem.
`Nexus Schema Typegen: Expected module dist\context.js to be an absolute path to a TypeScript module, skipping.
Server started, listening on port 4444 for incoming requests.
Missing required typegen import: Context`

**Comment by imran-ib** [comment] 2020-07-31 07:06
I am Not Sure Weather its good or bad but i fixed by removing Context type and source from schema.ts
**Before**
 `  typegenAutoConfig: {
    contextType: 'Context.Context',
    sources: [
      {
        source: '@prisma/client',
        alias: 'prisma',
      },
      {
        source: require.resolve('./context'),
        alias: 'Context',
      },
    ],
  },`

**after** 
` typegenAutoConfig: {
    sources: [
      {
        source: '@prisma/client',
        alias: 'prisma',
      },
    ],
  },`

**Comment by kierangilliam** [comment] 2020-08-18 06:03
I'm having this same issue using the nexus / prisma / apollo template.

**Comment by jamesguan** [comment] 2020-10-11 16:20
> In case you all haven't already fixed this, you can resolve the issue by renaming context.js to context.ts (you may need to support typescript imports in your main app)

This doesn't seem to be the right approach. Prisma should theoretically support both .js and .ts and should be language agnostic. The right approach would be to fix the code to accept both .js and .ts files.

**Comment by fullStackDataSolutions** [comment] 2020-10-20 18:47
@jamesguan The problem is that the Context file should be the ts type definition for the context. This enables auto completion and code checking, which makes life much easier. It's completely worth going through the effort to write the server in TS.

**Comment by ibash** [comment] 2020-10-26 00:49
Make a file:
```typescript
// context.d.ts
export type Context = {}
```

And make typegen point to it instead:
```
// change...
// source: require.resolve('./context'),
// to...
source: require.resolve('./context.d.ts'),
```

**Comment by chrisbull** [comment] 2020-11-16 13:45
Instead of creating a new file, you can just point to the correct folder using: 
```
source: `${__dirname.replace(/\/dist$/, '/src')}/context.ts`,
```

**Comment by ruheni** [comment] 2023-02-01 14:19
Hey, we've made a few updates to the example which should fix this. Feel free to re-open the issue if you're still running into it. :)

**Closed by ruheni** 2023-02-01 14:19 UTC
Labels: kind/bug, bug/0-unknown
