### ISSUE TITLE
graphql-nextjs: Can't write schema.graphql to file system (Error: EACCES: permission denied, open '/schema.graphql')

### ISSUE THREAD

**Issue by ajmajma** [prisma/prisma-examples#1543] opened 2020-02-27 19:08 UTC
Hey all,

Trying to fool around with the graphql-nextjs example to get myself acquainted - but I am seeing  problems in the console. In the console I am seeing 

```
[Error: EACCES: permission denied, open '/schema.graphql'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/schema.graphql'
}
```

This is a fresh install as of today. Using node 13.7.0 if this helps.

**Comment by nikolasburk** [comment] 2020-02-28 16:11
Hey @ajmajma, thanks a lot for opening this issue. I just checked and the error doesn't seem problematic. For some reason Nexus isn't able to write the `schema.graphql` file to the file system. 

I changed the title of this issue to reflect that.

**Comment by ajmajma** [comment] 2020-02-28 16:48
Hey @nikolasburk  thanks for updating this. I don't know if this is related but the `generate:nexus` seems to also be breaking. When I try to run it, the console is giving me : 

```
(node:32915) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/amoser/Desktop/prisma-examples-prisma2 3/typescript/graphql-nextjs/pages/api/index.ts:1
import { idArg, makeSchema, objectType, stringArg, asNexusMethod } from 'nexus';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by JorgeCeja** [comment] 2020-03-02 19:33
The problem is with `"module"` from tsconfig.json. If you switch from `"module":"esnext"` to `"module": "commonjs"` the issue is fixed. However, nextjs requires esnext for dynamic import() support. 

This is just a workaround, it'll be great to find a solution that works for both nextjs and nexus.

P.S. I'm also running into 'Error: EACCES: permission denied, open '/schema.graphql'' issue with node 10

**Comment by yassinebridi** [comment] 2020-04-04 21:05
This is probably obvious,
but as a workaround, i executed yarn dev with sudo privileges.
@JorgeCeja when i change the module to commonjs, the compiler tries to edit the module back to esnext.

**Comment by Edjevw12** [comment] 2020-04-06 07:50
I changed `__dirname` to `process.cwd()` and it worked for me. 

`const schema = makeSchema({
  types: [Query, Mutation, User],
  outputs: {
    typegen: process.cwd() + '/pages/api/nexus-typegen.ts',
    schema: process.cwd() + '/pages/api/schema.graphql',
  },
});`

**Comment by nikolasburk** [comment] 2020-04-06 07:57
@Edjevw12 do you mind submitting a PR with this solution 🙂

**Comment by akshaylive** [comment] 2020-05-04 20:23
FWIW, I've created a [PR](https://github.com/prisma/prisma-examples/issues/1543) that fixes this and a few related issues.

**Comment by nikolasburk** [comment] 2020-05-05 06:37
Thanks a lot @akshaylive, the PR is merged 🚀

**Closed by nikolasburk** 2020-05-05 06:37 UTC
