### ISSUE TITLE
Tests should report failure if 1 of the tests fails

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1659] opened 2020-03-28 04:47 UTC
Right now Actions reports the tests are succeeding, although they are clearly failing:

https://github.com/prisma/prisma-examples/issues/1652
https://github.com/prisma/prisma-examples/issues/1651

That is dangerous, as one does not really see when stuff goes wrong.

Fundamentally there are 2 problems:
1. All tests are run in one batch, a suggestion to change that is at https://github.com/prisma/prisma-examples/issues/1653
2. Even when one of the tests clearly fails, the test run still reports a success as a whole.

If one of the tests fails, the run should report a failure as a whole.

**Comment by steebchen** [comment] 2020-03-28 07:50
The problem is within the tests themselves, not in the general test scheme. The errors you see in the log output have different reasons: one unfortunate mistake from me is misunderstanding Promises which is fixed via https://github.com/prisma/prisma-examples/pull/1661; most other errors are more like warnings and don't have any influence. For example, for graphql test, we send a GraphQL request using curl so if that succeeds it doesn't matter what the server reports; as long as the request succeeds without an error it's fine, but of course it would be much better if we would actually test for the result – which we can of course do but is more work.

**Comment by janpio** [comment] 2020-03-28 15:01
Right now the situation is that I get a passing workflow. Looking into the output of that, I see all kinds of errors - both real errors and not real errors. In https://github.com/prisma/prisma-examples/issues/1651 the stuff might be cosmetic an what you describe, but https://github.com/prisma/prisma-examples/issues/1652 many tests are really totally broken.

That is what we need to fix.

**Comment by steebchen** [comment] 2020-03-30 16:15
Can this be closed?

**Closed** 2020-10-29 10:43 UTC
Labels: kind/improvement, team/other
